# _quarto.yml
project:
  type: website
  output-dir: ../_site/en

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - href: research/index.qmd
        text: Research
      - href: teaching/index.qmd
        text: Teaching
    right:
      - text: FR
        url: "https://antoineboulet.github.io/fr/index.html"

format:
  html:
    theme: cosmo
    math: mathjax
    toc: true