# _quarto.yml
project:
  type: website
  output-dir: ../_site/en

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: research
        href: research/index.qmd
      - text: publications
      - text: lectures
        href: teaching/index.qmd
      - text: codes
    right:
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+research@protonmail.com

format:
  html:
    theme: cosmo
    lang: en
    math: mathjax
    toc: true