# _quarto.yml
project:
  title: "Antoine Boulet"
  output-dir: ./_site/en

website:
  navbar:
    left:
      - text: research
        menu: 
          - text: overview & highlights
            href: research/overview-highlights.qmd
          - text: publications & preprints
            href: research/publications-preprints.qmd
          - text: talks & lectures
            href: research/talks-lectures.qmd
          - text: code & tools
            href: research/code-tools.qmd
      - text: teaching
        href: teaching/index.qmd 
      - text: notebook
    tools:
      - icon: file-earmark-person
        text: "curriculum vitæ (EN)"
        href: cv.qmd
      - icon: translate 
        text: "Toggle in french (FR)"
        href: ../fr
      

lang: en

format:
  html:
    lang: en-US

