# _quarto.yml
project:
  title: "ABT-FR"
  output-dir: ./_site/fr

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: recherche
      - text: enseignement
    right:
      - text: EN
        href: ../en
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+research@protonmail.com

lang: fr

format:
  html:
    theme: cosmo
    lang: fr-CA
    math: mathjax