project:
  type: website
  
profile:
  default: en
  group: [en, fr]

format:
  html:
    include-in-header:
      - system/includes/icons.html

metadata-files: 
  - system/fragments/default-header.yml
  - system/fragments/default-theme.yml
  - system/fragments/default-website.yml
  - system/fragments/portfolio-header.yml
  - system/fragments/portfolio-theme.yml
  - system/fragments/portfolio-website.yml
    