# _quarto-fr.yml

render:
    - fr/**/*.qmd
    - index.qmd
    
website:
  title: "Antoine Boulet"
  navbar:
    left:
      - href: fr/research/index.qmd
        text: Recherche
      - href: fr/teaching/index.qmd
        text: Enseignement
    right:
      - text: EN
        href: en/index.qmd