# _quarto.yml
project:
  title: "ABT-FR"
  output-dir: ./_site/fr

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: recherche
      - text: enseignement
        menu:
          - text: CP A1 & A2
          - text: physique générale
            href: teaching/general-physics.qmd
          - text: CI A3 FISE
          - text: structure de la matière
            href: teaching/structure-of-matter.qmd
          - text: mécanique quantique
            href: teaching/quantum-mechanics.qmd
          - text: CI A3 FISA
          - text: outils mathématiques
            href: teaching/mathematical-tools.qmd
          - text: équations différentielles
            href: teaching/differential-equations.qmd
      - text: blog
    right:
      - text: EN
        href: ../en
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+research@protonmail.com

lang: fr

format:
  html:
    theme: cosmo
    lang: fr-CA
    math: mathjax