project:
  type: website
  
profile:
  default: en
  group: [en, fr]

format:
  html:
    include-in-header:
      - system/includes/icons.html

metadata-files: 
  - system/fragments/default.yml
  - system/fragments/portfolio.yml
    