# _quarto-en.yml
project:
  render:
    - en/**/*.qmd
  #output-dir: _site        # ← en/ va dans _site/en/

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - href: en/research/index.qmd
        text: Research
      - href: en/teaching/index.qmd
        text: Teaching
    right:
      - text: FR
        href: fr/index.qmd