# _quarto.yml
project:
  title: "ABT-EN"
  output-dir: ./_site/en

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: research
        menu: 
          - text: overview & highlights
            href: research/overview-highlights.qmd
          - text: publications & preprints
            href: research/publications-preprints.qmd
          - text: talks & lectures
            href: research/talks-lectures.qmd
          - text: code & tools
            href: research/code-tools.qmd
      - text: teaching
      - text: notebook
    right:
      - text: FR
        href: ../fr
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+research@protonmail.com

lang: en

format:
  html:
    theme: cosmo
    lang: en-US
    math: mathjax