# _quarto.yml
project:
  title: "ABT-EN"
  output-dir: ./_site/en

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: research
      - text: teaching
    right:
      - text: FR
        href: ../fr
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+research@protonmail.com

lang: en

format:
  html:
    theme: cosmo
    lang: en-US
    math: mathjax