# _quarto.yml
project:
  title: "Antoine Boulet"
  output-dir: ./_site/fr

website:
  navbar:
    left:
      - text: recherche
      - text: enseignement
        menu:
          - text: CP A1 & A2
          - text: physique générale
            href: teaching/general-physics.qmd
          - text: CI A3 FISE
          - text: structure de la matière
            href: teaching/structure-of-matter.qmd
          - text: mécanique quantique
            href: teaching/quantum-mechanics.qmd
          - text: CI A3 FISA
          - text: outils mathématiques
            href: teaching/mathematical-tools.qmd
          - text: équations différentielles
            href: teaching/differential-equations.qmd
      - text: blog
    tools:
      - icon: file-earmark-person
        text: "curriculum vitæ (FR)"
        href: cv.qmd
      - icon: translate 
        text: "Basculer en anglais (EN)"
        href: ../en
  

lang: fr

format:
  html:
    lang: fr-FR
