# _quarto-fr.yml

project:
  render:
    - fr/**/*.qmd
    - index.qmd
  output-dir: _site        # ← fr/ va dans _site/fr/

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - href: fr/research/index.qmd
        text: Recherche
      - href: fr/teaching/index.qmd
        text: Enseignement
    right:
      - text: EN
        href: en/index.qmd