# _quarto.yml
project:
  type: website
  output-dir: ../_site/fr

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - href: research/index.qmd
        text: Recherche
      - href: teaching/index.qmd
        text: Enseignement
    right:
      - text: EN
        href: "../en/index.html"

format:
  html:
    theme: cosmo
    math: mathjax
    toc: true