# _quarto.yml
project:
  type: website
  output-dir: ../_site/fr

website:
  title: "Antoine Boulet"
  navbar:
    left:
      - text: recherche
        href: recherche/index.qmd
      - text: enseignement
        href: enseignement/index.qmd
      - text: blog
        href: blog/index.qmd
        
    right:
      - text: "{{< ai cv >}}"
        href: "https://orcid.org/0000-0003-3839-6090"
      - text: "{{< fa at >}}"
        href: mailto:antoine.boulet+enseignement@protonmail.com

format:
  html:
    theme: cosmo
    lang: fr
    math: mathjax
    toc: true