name: publish-website

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render FR
        run: |
          quarto render --profile fr
          mv _site _site_fr

      - name: Render EN
        run: |
          quarto render --profile en
          mv _site _site_en

      - name: Merge
        run: |
          mkdir -p _site
          cp -r _site_fr/* _site/
          cp -r _site_en/en _site/en
          rm -rf _site_fr _site_en

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site